name: ci

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.0.1'
          elixir-version: '1.13.4'
      - uses: actions/checkout@v2
      - name: Cache Mix Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-
          path: |
            ./_build
            ./deps
      - name: Fetch Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile --all-warnings --warning-as-errors

  code-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.0.1'
          elixir-version: '1.13.4'
      - uses: actions/checkout@v2
      - name: Cache Mix Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-
          path: |
            ./_build
            ./deps
      - name: Cache PLTs
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-plts-
          path: ./priv/plts
      - name: Check Format
        run: mix format --check-formatted
      - name: Run Credo
        run: mix credo
      - name: Run Dialyzer
        run: mix dialyzer

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.0.1'
          elixir-version: '1.13.4'
      - uses: actions/checkout@v2
      - name: Cache Mix Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-
          path: |
            ./_build
            ./deps
      - name: Cache Test Build
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-test-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-test-
          path: ./_build
      - name: Compile Test
        run: mix compile --all-warnings --warning-as-errors
        env:
          MIX_ENV: test
      - name: Run Tests
        run: mix test --warnings-as-errors
