name: publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0.2'
          elixir-version: '1.13.1'
      - uses: actions/checkout@v2
      - name: Cache Mix Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-
          path: |
            ./_build
            ./deps
      - name: Fetch Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile --all-warnings --warning-as-errors

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0.2'
          elixir-version: '1.13.1'
      - uses: actions/checkout@v2
      - name: Cache Mix Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-
          path: |
            ./_build
            ./deps
      - name: Cache Test Build
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-test-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-test-
          path: ./_build
      - name: Compile Test
        run: mix compile --all-warnings --warning-as-errors
        env:
          MIX_ENV: test
      - name: Run Tests
        run: mix test --warnings-as-errors

  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0.2'
          elixir-version: '1.13.1'
      - uses: actions/checkout@v2
      - name: Cache Mix Artifacts
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-
          path: |
            ./_build
            ./deps
      - name: Publish Hex Package
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish --yes
